services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    secrets:
      - db_password
      - credentials
    restart: always

  nginx:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx
    env_file: .env
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lprieri/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lprieri/data/wordpress

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt